spring:
    application:
      name: fc-eda-spring-boot
    datasource:
      username: postgres
      password: postgres
      url: jdbc:postgresql://challenge-database:5432/challenge
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 3003
