// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course_category.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{0}
}

func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (m *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(m, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

type Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateCategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{2}
}

func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(m, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CategoryList struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoryList) Reset()         { *m = CategoryList{} }
func (m *CategoryList) String() string { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()    {}
func (*CategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{3}
}

func (m *CategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryList.Unmarshal(m, b)
}
func (m *CategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryList.Marshal(b, m, deterministic)
}
func (m *CategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryList.Merge(m, src)
}
func (m *CategoryList) XXX_Size() int {
	return xxx_messageInfo_CategoryList.Size(m)
}
func (m *CategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryList proto.InternalMessageInfo

func (m *CategoryList) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CategoryGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryGetRequest) Reset()         { *m = CategoryGetRequest{} }
func (m *CategoryGetRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryGetRequest) ProtoMessage()    {}
func (*CategoryGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde79cb73866aac8, []int{4}
}

func (m *CategoryGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryGetRequest.Unmarshal(m, b)
}
func (m *CategoryGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryGetRequest.Marshal(b, m, deterministic)
}
func (m *CategoryGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryGetRequest.Merge(m, src)
}
func (m *CategoryGetRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryGetRequest.Size(m)
}
func (m *CategoryGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryGetRequest proto.InternalMessageInfo

func (m *CategoryGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Blank)(nil), "pb.Blank")
	proto.RegisterType((*Category)(nil), "pb.Category")
	proto.RegisterType((*CreateCategoryRequest)(nil), "pb.CreateCategoryRequest")
	proto.RegisterType((*CategoryList)(nil), "pb.CategoryList")
	proto.RegisterType((*CategoryGetRequest)(nil), "pb.CategoryGetRequest")
}

func init() {
	proto.RegisterFile("proto/course_category.proto", fileDescriptor_fde79cb73866aac8)
}

var fileDescriptor_fde79cb73866aac8 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0xbb, 0xd4, 0x7f, 0x1d, 0x2a, 0x9a, 0x89, 0x1a, 0xd4, 0x0b, 0xd9, 0x78, 0xe0, 0x60,
	0x20, 0xa9, 0xf1, 0xa4, 0xa7, 0x72, 0xe0, 0xa2, 0x89, 0x69, 0x6f, 0x5e, 0xcc, 0x02, 0x13, 0xb3,
	0xb1, 0x05, 0x5c, 0xb6, 0x26, 0x7e, 0x7a, 0x0d, 0x9b, 0x82, 0x50, 0xab, 0xb7, 0xc9, 0x9b, 0xc7,
	0x6f, 0xde, 0x03, 0xe0, 0xb2, 0x54, 0x85, 0x2e, 0xc2, 0xb4, 0x58, 0xa9, 0x8a, 0x5e, 0x52, 0xa1,
	0xe9, 0xb5, 0x50, 0x9f, 0x81, 0x51, 0xd1, 0x2a, 0x13, 0xbe, 0x0f, 0xbb, 0xd3, 0x85, 0xc8, 0xdf,
	0xf8, 0x13, 0x1c, 0x44, 0xeb, 0x35, 0x3a, 0x60, 0xc9, 0xcc, 0x65, 0x1e, 0xf3, 0x47, 0x33, 0x4b,
	0x66, 0x88, 0xb0, 0x93, 0x8b, 0x25, 0xb9, 0x96, 0x51, 0xcc, 0x8c, 0x1e, 0xd8, 0x19, 0x55, 0xa9,
	0x92, 0xa5, 0x96, 0x45, 0xee, 0x0e, 0xcd, 0xaa, 0x2b, 0xf1, 0x47, 0x38, 0x8d, 0x14, 0x09, 0x4d,
	0x0d, 0x77, 0x46, 0xef, 0x2b, 0xaa, 0x74, 0x8b, 0x63, 0x7f, 0xe3, 0xac, 0xdf, 0xb8, 0x7b, 0x18,
	0x37, 0xa0, 0x07, 0x59, 0x69, 0xbc, 0x06, 0x58, 0xf7, 0x91, 0x54, 0xb9, 0xcc, 0x1b, 0xfa, 0xf6,
	0x64, 0x1c, 0x94, 0x49, 0xd0, 0x9e, 0xeb, 0xec, 0xf9, 0x15, 0x60, 0xa3, 0xc7, 0xa4, 0x9b, 0x24,
	0x1b, 0x45, 0x27, 0x5f, 0x0c, 0x8e, 0x1a, 0xdb, 0x9c, 0xd4, 0x87, 0x4c, 0x09, 0xef, 0xc0, 0xe9,
	0xd7, 0xc0, 0x73, 0x73, 0x65, 0x5b, 0xb5, 0x8b, 0x5e, 0x00, 0x3e, 0xc0, 0x18, 0x4e, 0xfa, 0xc6,
	0xb9, 0x56, 0x24, 0x96, 0xff, 0x21, 0x8e, 0xbb, 0x88, 0xba, 0x29, 0x1f, 0xf8, 0x0c, 0x43, 0x70,
	0xea, 0x39, 0x6a, 0x1b, 0xe1, 0xa8, 0xf6, 0x99, 0x6f, 0xb7, 0xed, 0x11, 0xbc, 0x05, 0x3b, 0x26,
	0xdd, 0x66, 0x3e, 0xeb, 0x5a, 0x7e, 0xde, 0xc0, 0x66, 0xe0, 0xe9, 0xe1, 0xb3, 0x2d, 0x73, 0x4d,
	0x2a, 0x17, 0x8b, 0xb0, 0x4c, 0x92, 0x3d, 0xf3, 0xa7, 0xdc, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xe3, 0x2d, 0xb2, 0x80, 0x48, 0x02, 0x00, 0x00,
}
