apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 10
  template: 
    metadata:
      labels: 
        app: "goserver"
    spec: 
      containers: 
        - name: goserver
          image: "rodrigolucio/hello-go:v4"
          env:
            - name: my_host
              value: "1.2.3.4" 
            - name: my_port
              value: "5432"
            - name: my_database
              value: "order"