apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 1
  template: 
    metadata:
      labels: 
        app: "goserver"
    spec: 
      containers: 
        - name: goserver
          image: "rodrigolucio/hello-go:v5.3.1"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000 # Porta do container
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10 # aguarda 10 segundos para começar a verificação

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000 # Porta do container
            periodSeconds: 5 # Faz a verificação a cada 5 segundos do healthz
            failureThreshold: 1 # Quantas vezes tem que dar problema para ele reiniciar
            timeoutSeconds: 1 # Quanto tempo ele espera o health
            successThreshold: 1 #Quantas vezes ele testa para ter certeza que esta OK, famoso teste para garantir
            initialDelaySeconds: 15

          envFrom:
            - configMapRef:
                name: goserver-env #Carrega todas as variaveis de ambiente do arquivo configmap-env.yaml, sem precisar declarar todas aqui em baixo novamente
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myconfs"
              name: config

      volumes: 
        - name: config
          configMap:
            name: configmap-myconfs
            items:
            - key: my_database
              path: "myconfs.txt"