apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 1
  template: 
    metadata:
      labels: 
        app: "goserver"
    spec: 
      containers: 
        - name: goserver
          image: "rodrigolucio/hello-go:v5.3"
          envFrom:
            - configMapRef:
                name: goserver-env #Carrega todas as variaveis de ambiente do arquivo configmap-env.yaml, sem precisar declarar todas aqui em baixo novamente
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myconfs"
              name: config

      volumes: 
        - name: config
          configMap:
            name: configmap-myconfs
            items:
            - key: my_database
              path: "myconfs.txt"