apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: goserver
    kind: Deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25 #normalmente é bom deixar entre 75 e 80
