apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-somenteleitura
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"] #apiGroups de deployments é o apps
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-somenteleitura-bind
subjects:
  - kind: ServiceAccount
    name: server
    namespace: prod
roleRef:
  kind: Role
  name: server-somenteleitura
  apiGroup: rbac.authorization.k8s.io

# Basicamente aqui foi definido um ServiceAccount, criado uma regra
# De somente leitura de pods, services e deployments
# E feito o bind do ServiceAccount com a Role no RoleBinding